/*
 * proc.h — processes, scheduling and signals. (GPLv2)
 *
 * A process owns an address space, a kernel stack, a file-descriptor table
 * and a place in a process group.  Process groups are what make job control
 * possible: the tty remembers one "foreground" group, signals generated by
 * the keyboard go to every member of it, and everyone else is either running
 * quietly in the background or stopped.
 */
#ifndef GNUCOS_PROC_H
#define GNUCOS_PROC_H

#include <stdint.h>

#include "vmm.h"
#include "panic.h"

/*
 * 64 rather than 16.  A single OpenRC runlevel forks openrc, openrc-run, a
 * shell per service and start-stop-daemon for each backgrounded one, and an
 * interactive bash pipeline adds a process per stage on top -- 16 was being
 * exhausted before the runlevel finished.  The cost is linear and paid in
 * BSS: KSTACK_SIZE * MAX_PROCS (1 MiB) plus sizeof(proc_t) * MAX_PROCS
 * (~340 KiB), which is why the QEMU line went from -m 256M to -m 512M.
 */
#define MAX_PROCS     64
#define KSTACK_SIZE   0x4000        /* 16 KiB */

/* A full libc program opens far more descriptors than the toy utilities did:
 * BusyBox's `cp -a` alone holds a source fd, a destination fd and a directory
 * fd per recursion level, and musl keeps stdio buffers on top.  64 is cheap
 * (an int each) and removes the ceiling as a thing to think about. */
#define PROC_MAX_FD   64

/* Supplementary groups per process.  Linux allows 65536; 32 is what a login
 * on a machine with a handful of accounts will ever install, and it keeps the
 * PCB (already ~340 KiB across MAX_PROCS) from growing another 256 KiB. */
#define PROC_NGROUPS  32

/* Process states.  STOPPED is distinct from BLOCKED: a stopped process is
 * not waiting for anything, it has been suspended by a job-control signal
 * and only SIGCONT will bring it back. */
typedef enum {
    PROC_UNUSED = 0,
    PROC_READY,
    PROC_RUNNING,
    PROC_BLOCKED,
    PROC_STOPPED,
    PROC_ZOMBIE,
} proc_state_t;

/* Why a BLOCKED process is blocked. */
typedef enum {
    WAIT_NONE = 0,
    WAIT_CHILD,
    WAIT_TTY,
    WAIT_PIPE,
    WAIT_NET,
    WAIT_SLEEP,                     /* nanosleep: waiting only on the clock */
    WAIT_FUTEX,                     /* futex wait: keyed by (as, futex_addr) */
    WAIT_DRM,                       /* DRM wait_queue (vblank/commit/event) */
} wait_reason_t;

/* Signal numbers, wait() flags and the rest of the user-visible constants
 * come from the shared contract header, so the kernel cannot disagree with
 * the programs it runs. */
#include "sysnum.h"

/* 64 rather than 32 because that is the width musl talks in: every
 * rt_sigprocmask/rt_sigaction it issues carries sigsetsize == 8. */
#define NSIG    64

/* Linux/musl put signal N at bit (N-1) of a sigset, so SIGUSR1 (10) is bit
 * 9 and SIGUSR2 (12) is bit 11.  Matching that convention end-to-end is what
 * lets a sigset the libc fills in and the one the kernel masks on actually
 * refer to the same signal. */
#define SIGMASK(n) (1ull << ((uint64_t)(n) - 1))

/* One disposition, in the shape the kernel/user rt_sigaction ABI uses.  Note
 * this is the *kernel's* 32-byte struct sigaction, not the 152-byte one in
 * <signal.h>; musl translates between the two. */
typedef struct {
    uint64_t handler;           /* SIG_DFL, SIG_IGN, or a user address */
    uint64_t flags;             /* SA_* */
    uint64_t restorer;          /* required when handler is a real address */
    uint64_t mask;              /* extra signals blocked during the handler */
} sigact_t;

typedef struct proc {
    int           pid;
    int           ppid;
    /*
     * Thread group id: pid of the group leader.  A plain fork gives the
     * child tgid == its own pid; clone(CLONE_THREAD) copies the parent's
     * tgid, so every thread of a process reports one getpid() while
     * gettid() still tells them apart.  The leader (pid == tgid) is the
     * process the parent waits on and the one that becomes the group's
     * zombie.
     */
    int           tgid;
    /*
     * Set on every member while the thread group is being torn down (exit,
     * exit_group, exec from a multithreaded process, fatal signal).  A
     * thread that gets scheduled with this set never returns to user mode:
     * proc_check_signals() turns it into a zombie on the way out instead.
     */
    int           group_dying;
    /*
     * The futex word this process sleeps on while blocked in WAIT_FUTEX,
     * paired with `as`: two address spaces waiting on the same virtual
     * address (different physical pages!) must never confuse each other.
     */
    uint64_t      futex_addr;
    int           pgid;             /* process group: the unit of job control */
    /*
     * Session id.  A session is a collection of process groups that share a
     * controlling terminal; setsid() starts a new one.  We track it mainly so
     * a daemon that has detached (start-stop-daemon --background does exactly
     * this) can be told apart from the shell's own jobs, and so TIOCSPGRP
     * from outside the tty's session can be refused the way Linux does.
     */
    int           sid;

    /*
     * The controlling terminal: an index into the virtual-terminal array, or
     * -1 for "none".  A process inherits it across fork and exec, setsid()
     * drops it, and TIOCSCTTY on an open /dev/ttyN claims that one.  This is
     * what gives /dev/tty a meaning once there is more than one terminal --
     * without it, a shell on tty3 opening /dev/tty would get whichever
     * console the user happens to be looking at.
     */
    int           ctty;

    /*
     * Credentials.  Real / effective / saved-set, for both user and group,
     * exactly the POSIX triple: the real id is who you are, the effective id
     * is what the kernel checks permissions against, and the saved id is what
     * a set-user-ID program may switch back to after dropping privilege.
     * `groups` is the supplementary set login(1) installs from /etc/group.
     */
    uint32_t      uid,  euid,  suid;
    uint32_t      gid,  egid,  sgid;
    uint32_t      ngroups;
    uint32_t      groups[PROC_NGROUPS];

    proc_state_t  state;
    wait_reason_t wait_reason;
    int           wait_pid;         /* which child waitpid() is after, -1 = any */
    uint64_t      wake_tick;        /* timer tick to wake at, 0 = no deadline */
    void         *wait_q;           /* DRM wait_queue this proc sleeps on */

    /* The tick this process was created on.  There is no per-process CPU
     * accounting here, so times() and getrusage() report elapsed lifetime
     * instead; a shell's `time` builtin subtracts two samples, and for that
     * a monotonic baseline is all it needs. */
    uint64_t      start_tick;

    /* ITIMER_REAL, in scheduler ticks.  It counts wall-clock time, so unlike
     * wake_tick it keeps running while the process is descheduled -- which is
     * the point of alarm(): interrupting a call that is stuck. */
    uint64_t      itimer_expire;    /* tick to raise SIGALRM at, 0 = off */
    uint64_t      itimer_interval;  /* re-arm period in ticks, 0 = one-shot */

    addrspace_t  *as;
    uint64_t      kstack_top;
    uint64_t      saved_rsp;        /* where switch_context parked this task */

    int           fds[PROC_MAX_FD]; /* -1, or a handle into the open-file table */

    /*
     * Close-on-exec, one bit per descriptor.  This is a property of the
     * descriptor and not of the open file behind it, which is exactly why it
     * cannot live in the VFS table: two fds dup'd onto the same file may
     * disagree about it, and dup2() is defined to clear the bit on the new fd
     * even when the old one has it set.  A bitmap works because PROC_MAX_FD
     * is 64; the assertion below is what keeps that true.
     */
    uint64_t      fd_cloexec;

    uint64_t      sig_pending;
    uint64_t      sig_ignored;
    uint64_t      sig_mask;         /* signals blocked from delivery */
    sigact_t      sigact[NSIG];     /* installed dispositions */

    /*
     * sigsuspend(2) swaps in a temporary mask, waits for a signal, and must
     * put the caller's original mask back *after* the handler has run -- not
     * before, or the handler would be delivered under a mask that very likely
     * blocks the signal it is waiting for.  Linux solves this with
     * TIF_RESTORE_SIGMASK; this is the same trick: sigsuspend parks the old
     * mask here, and signal_deliver() writes it into the frame's uc_sigmask
     * so rt_sigreturn restores it instead of the suspend mask.
     */
    uint64_t      sig_saved_mask;
    int           sig_restore_mask;

    /* The syscall number the current trap came in with, or -1 when the trap
     * is not a restartable syscall.  syscall_handler() overwrites RAX with
     * the result before anyone gets to look at signals, so SA_RESTART needs
     * its own copy to rewind to. */
    int64_t       syscall_nr;

    uint64_t      brk;              /* current data break (sbrk/brk) */
    uint64_t      fs_base;          /* TLS base (arch_prctl ARCH_SET_FS) */
    uint64_t      clear_child_tid;  /* set_tid_address: futex word to clear */

    /* Ring of the last 8 syscalls (nr + return), dumped by the fault handler
     * so a NULL-deref crash shows what the process was doing. */
    uint16_t      sys_hist_nr[8];
    int32_t       sys_hist_ret[8];
    uint8_t       sys_hist_idx;

    /* Per-process FPU/SSE state.  fxsave needs the buffer 16-byte aligned,
     * so the field carries that alignment and the whole struct inherits it. */
    uint8_t       fpu[512] __attribute__((aligned(16)));

    /* ---- EEVDF scheduling --------------------------------------------
     * Virtual run time in ticks, the global virtual clock, and the virtual
     * deadline (vruntime + slice) the run queue's binary heap is keyed on.
     * All weights are 1, so virtual time is just the CPU time a process
     * has consumed.  `rq_index` is the process's slot in the heap, -1 while
     * not queued; `bkl_held` records whether this process's kernel
     * execution owns the big kernel lock, so the answer survives a context
     * switch; `on_cpu` is the core running it (or -1).  The block is 48
     * bytes so the whole struct stays a multiple of 16 (fpu's alignment). */
    uint64_t      vruntime;       /* CPU time consumed, in ticks         */
    uint64_t      deadline;       /* vruntime + slice when last granted  */
    uint64_t      slice;          /* slice granted per pick, in ticks    */
    uint64_t      last_run_tick;  /* tick the CPU was last handed over   */
    int           rq_index;       /* heap slot, -1 when not queued       */
    int           bkl_held;       /* this kernel execution owns the BKL  */
    int           on_cpu;         /* core this process runs on, or -1    */
    int           rsvd;

    /*
     * The current directory, stored as a normalised absolute path rather than
     * as a pinned inode.  A path costs a string compare on every relative
     * lookup, but it makes getcwd() a memcpy and it cannot go stale when the
     * directory is renamed out from under us -- and on a read-mostly initrd
     * that trade is entirely in our favour.  Always begins with '/' and never
     * ends with one, except for the root itself.
     */
    char          cwd[GNUOS_PATH_MAX];

    /* File-creation mask.  We do not enforce permissions, but programs read
     * it back (umask(0) then umask(old) is a standard idiom), so it has to be
     * remembered per process and inherited across fork and exec. */
    uint32_t      umask;

    int           exit_status;
    int           term_sig;         /* non-zero if a signal killed us */
    int           stop_sig;         /* the signal that suspended us */
    int           reported;         /* stop already reported to the parent */

    /* ---- ptrace ------------------------------------------------------
     * A traced process hands every signal it would otherwise dispose of
     * to its tracer first, as a PROC_STOPPED stop whose wait status is
     * 0x7F | (stop_sig << 8) -- reported to the tracer by waitpid() with
     * no WUNTRACED needed.  The tracer must be the parent (see ptrace.c:
     * that is the one simplification this kernel makes over Linux, and it
     * lets the whole mechanism ride on the existing waitpid/zombie path).
     * ptrace_stopped distinguishes a ptrace stop from an ordinary job-
     * control stop: only PTRACE_CONT/SYSCALL/DETACH may resume one, and
     * SIGCONT must not.  While stopped, a regs_t snapshot lives in
     * ptrace_regs so GETREGS/SETREGS and the CONT-time replay never have
     * to touch the live kernel stack frame. */
    int           traced;           /* a parent is tracing us */
    int           tracer_pid;       /* who waitpid()s our stops and exit */
    int           ptrace_opts;      /* PTRACE_O_* (only TRACESYSGOOD) */
    int           ptrace_mode;      /* PTRACE_RUN_CONT / PTRACE_RUN_SYSCALL */
    int           ptrace_stopped;   /* in a ptrace stop, awaiting the tracer */
    int           ptrace_syscall_phase; /* 1 = entry stop done, exit pending */
    int           ptrace_resume_sig;    /* signal the tracer handed back */
    int           ptrace_regs_valid;    /* snapshot below is current */
    /* The stop image in Linux struct user_regs_struct layout -- exactly
     * what PTRACE_GETREGS/SETREGS exchange -- so the two never need a
     * translation of their own; the layout lives in ptrace.h, whose
     * conversion helpers cast this buffer.  27 qwords: r15..rdi (15),
     * orig_rax, then the seg/flag group. */
    uint64_t      ptrace_regs[27];

    char          name[16];

    /*
     * The full argument vector of the running image, NUL-separated and
     * NUL-terminated, in the layout /proc/<pid>/cmdline is defined to have.
     * OpenRC's start-stop-daemon identifies a running daemon by reading this
     * back and comparing it against the --exec it was asked to supervise, so
     * a plain basename in `name` is not enough.
     */
    char          cmdline[192];
    uint32_t      cmdline_len;
} proc_t;

/* fd_cloexec is a uint64_t bitmap indexed by descriptor number. */
_Static_assert(PROC_MAX_FD <= 64, "fd_cloexec bitmap is only 64 bits wide");

/* Write the current process's TLS base into MSR FSBASE.  Called by the two
 * paths that return to user mode (ret_to_user and the syscall stub) so a
 * process always runs with its own thread-local storage. */
void proc_set_fs(proc_t *p);

/* ---- lifecycle -------------------------------------------------------- */
void    proc_init(void);
proc_t *proc_current(void);
proc_t *proc_by_pid(int pid);

/* Build PID 1 from an executable in the filesystem and make it runnable. */
int  proc_spawn_init(const char *path);

/* fork(): duplicate the caller.  Returns the child's pid to the parent and
 * 0 to the child, or a negative errno. */
int  proc_fork(regs_t *r);

/* clone(2): the syscall musl funnels both fork() and pthread_create through.
 * CLONE_VM shares the parent's address space (threads, refcounted),
 * CLONE_THREAD puts the child in the parent's thread group; the libc-used
 * flags (TLS, parent/child tid, CLONE_CHILD_CLEARTID) are honoured too.
 * Returns the child pid to the parent and 0 to the child, or a negative
 * errno. */
int  proc_clone(regs_t *r);

/*
 * execve(): replace the caller's image.  Only returns on failure.
 *
 * argv and envp both point into the *caller's* address space, which this
 * function is about to destroy, so the strings are copied into kernel storage
 * before anything irreversible happens.  A `#!` script is resolved here too:
 * the interpreter becomes the real image and the script path is spliced into
 * argv, recursively, up to EXEC_INTERP_MAX levels deep.
 */
int  proc_execve(const char *path, char *const argv[], char *const envp[],
                 regs_t *r);

/* exit(): turn the caller into a zombie and schedule someone else. */
void proc_exit(int status) __attribute__((noreturn));

/*
 * Exit the caller's whole thread group.  Every member is marked dying and
 * woken; the group leader (pid == tgid) becomes the zombie its parent
 * waits on, carrying `status`.  Called from exit_group and, in a group
 * with only the leader left, from the leader's own exit.
 */
void proc_exit_group(int status) __attribute__((noreturn));

/* Wake every waiter on futex word `addr` inside address space `as`.
 * Returns how many were woken.  Used by futex(FUTEX_WAKE) and by the
 * pthread-exit path (clear_child_tid). */
int  proc_wake_futex(addrspace_t *as, uint64_t addr);

/* waitpid(): reap a child.  Blocks unless WNOHANG. */
int  proc_waitpid(int pid, int *status, int options);

/* ---- scheduling ------------------------------------------------------- */
void sched_start(void) __attribute__((noreturn));
void sched_yield(void);
void sched_tick(void);
void sched_block(wait_reason_t why);
/* Same, but the caller has already disabled interrupts and wants them left
 * that way -- the only race-free way for a driver to test "is there data?"
 * and go to sleep if there is not. */
void sched_block_irqoff(wait_reason_t why);
/* Block with a deadline, interrupts already off.  The sleeper is woken either
 * by whoever it is waiting for or by the timer after `ticks` ticks, whichever
 * comes first -- what a VTIME read needs so it can doze instead of spinning
 * (with nothing else runnable, a polling loop would burn a whole CPU). */
void sched_block_timeout(wait_reason_t why, uint64_t ticks);
void sched_wake(proc_t *p);
/* Wake everybody sleeping for the same reason (a driver got some data). */
void sched_wake_reason(wait_reason_t why);
void sched_wake_poll_channels(void);
/* Wake every process blocked on the given DRM wait_queue. */
void sched_wake_queue(void *q);
/* Wake anyone whose deadline has passed.  Called from the timer interrupt. */
void sched_expire_timeouts(void);

/* ---- kernel threads ----------------------------------------------------
 * A kthread is a task whose entry point is a kernel function rather than a
 * user program: it runs on the kernel page tables (vmm_kernel_as), owns no
 * user address space, and its first scheduling returns into
 * kthread_trampoline instead of ret_to_user.  kthread_create() hands the
 * bootstrap block to the trampoline, which runs entry(arg) and then exits
 * the thread. */
typedef struct kthread_bootstrap {
    void (*entry)(void *arg);
    void *arg;
} kthread_bootstrap_t;

void kthread_bootstrap(kthread_bootstrap_t *b) __attribute__((noreturn));
proc_t *kthread_create(const char *name, void (*entry)(void *), void *arg);

/* ---- signals ---------------------------------------------------------- */
int  proc_signal(proc_t *p, int sig);
int  proc_signal_group(int pgid, int sig);
void proc_check_signals(regs_t *r);

/*
 * The pending signals that should break a process out of a blocking call.
 *
 * SIGCHLD used to be excluded here, on the theory that a waitpid() returning
 * EINTR every time one of its own children exited would never reap anything.
 * That reasoning was right about the symptom and wrong about the cure: bash
 * deliberately installs its SIGCHLD handler *without* SA_RESTART precisely so
 * that a read() blocked at the prompt returns EINTR and the job table can be
 * updated.  Suppressing it kernel-side meant completed background jobs went
 * unreported until the user happened to press a key.  The exclusion now lives
 * where it belongs -- inside proc_waitpid(), which ignores its own SIGCHLD
 * and nothing else.
 */
uint64_t proc_pending_signals(const proc_t *p);

/*
 * True if `sig` would not actually stop or kill `p` right now, because the
 * process is ignoring it or has it blocked.  The terminal needs this: POSIX
 * says a background write that would raise SIGTTOU goes through unhindered
 * when the writer is ignoring or blocking the signal.  Without the exemption
 * a shell -- which ignores SIGTTOU precisely so it can hand the terminal back
 * and forth -- would deadlock against its own tty.
 */
int proc_signal_blocked(const proc_t *p, int sig);

/* ---- credentials ------------------------------------------------------- */
/*
 * True when `p` is a member of group `gid` -- either it is the effective
 * group or it appears in the supplementary set.  The permission check needs
 * this to decide whether a file's group bits apply.
 */
int proc_in_group(const proc_t *p, uint32_t gid);

/*
 * Permission test against a file's owner and mode bits.  `want` is a mask of
 * 4 (read), 2 (write) and 1 (execute), in the same encoding as the mode bits
 * themselves.  Returns 1 when the current process may proceed.
 *
 * Root is exempt from everything except "execute a file with no execute bit
 * set at all", which even root is refused -- that rule is what stops a stray
 * `./notes.txt` from being handed to the ELF loader.
 */
int proc_permitted(uint32_t mode, uint32_t uid, uint32_t gid, int want,
                   int is_dir);

#endif
